// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW_sLdkjyK3J6_5AXAyPnM0nk9RLAWJy8',
    appId: '1:117467033317:web:d07d742b8b1c4e10352e0c',
    messagingSenderId: '117467033317',
    projectId: 'lifedropbd2026',
    authDomain: 'lifedropbd2026.firebaseapp.com',
    storageBucket: 'lifedropbd2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7EfXQV-Eg_yS2bc1GLIho295hBnsA0gc',
    appId: '1:117467033317:android:4a6c5f70b937aa31352e0c',
    messagingSenderId: '117467033317',
    projectId: 'lifedropbd2026',
    storageBucket: 'lifedropbd2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-btrd4ncSlK3wut6mfkR_XFJ8BO5ncCY',
    appId: '1:117467033317:ios:ab1b7e22d3ea6d57352e0c',
    messagingSenderId: '117467033317',
    projectId: 'lifedropbd2026',
    storageBucket: 'lifedropbd2026.firebasestorage.app',
    iosBundleId: 'com.lifedrop.app.lifedrop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-btrd4ncSlK3wut6mfkR_XFJ8BO5ncCY',
    appId: '1:117467033317:ios:6c1a51ecbb48a448352e0c',
    messagingSenderId: '117467033317',
    projectId: 'lifedropbd2026',
    storageBucket: 'lifedropbd2026.firebasestorage.app',
    iosBundleId: 'com.lifedrop.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW_sLdkjyK3J6_5AXAyPnM0nk9RLAWJy8',
    appId: '1:117467033317:web:e27da23a0ca9c54a352e0c',
    messagingSenderId: '117467033317',
    projectId: 'lifedropbd2026',
    authDomain: 'lifedropbd2026.firebaseapp.com',
    storageBucket: 'lifedropbd2026.firebasestorage.app',
  );
}
